FROM ubuntu:24.04

RUN apt-get update && apt-get install -y socat && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN useradd -U -m -s /bin/bash ctf

COPY ./flag.txt /home/ctf/flag.txt
COPY ./chall /home/ctf/chall

WORKDIR /home/ctf

RUN chown -R root:ctf /home/ctf && chmod -R 550 /home/ctf

EXPOSE 1338

CMD ["socat", "-T60", "TCP-LISTEN:1338,reuseaddr,fork", "EXEC:/home/ctf/chall,stderr"]   
